############################################################################
#
#  Primary targets:
#    all           - the default target; synonym for 'coq'
#    coq           - builds all .vo files
#    doc           - synonym for 'documentation'
#    install       - copy to coq library location
#    clean         - removes generated files
#
############################################################################

## Paths to executables. Do not include options here.
## Modify these to suit your Coq installation, if necessary.

## If you get warnings such as:
## *** Warning: in file AssocList.v, library CoqFSetDecide is required and has not been found in the loadpath!
## you can use a shell variable to set the load path. (Somehow the -I below is being ignored.)
## export COQPATH=.

COQC = coqc
COQDEP = coqdep
COQDOC = coqdoc

MODULES	:= infra_nom ZtoConfl_nom lx_nom
TEX	:= $(MODULES:%=latex/%.v.tex)

## Library name used for the imports in Coq

LIBNAME=NomConfl

## Name of the submakefile generated by coq_makefile

COQMKFILENAME=CoqNom.mk

############################################################################

.PHONY: all clean coq doc
.SUFFIXES: .v .vo .v.d .v.glob

all: coq

%.mk : Makefile _%
	coq_makefile -f _$* -o $*.mk

$(COQMKFILENAME): Makefile
	{ echo "-R . $(LIBNAME) " ; ls *.v ; } > _CoqProject && coq_makefile -f _CoqProject -o $(COQMKFILENAME)

coq: $(COQMKFILENAME)
	cd Metalib && $(MAKE)
	@$(MAKE) -f $(COQMKFILENAME)

install: all
	@$(MAKE) -f $(COQMKFILENAME) install

clean:
	@$(MAKE) -f $(COQMKFILENAME) clean
	rm -if $(COQMKFILENAME)

doc: latex/report.pdf

latex/%.v.tex: Makefile %.v %.glob
	 $(COQDOC) --gallina --interpolate --latex --body-only -s \
		$*.v -o latex/$*.v.tex

latex/report.pdf: latex/report.tex $(TEX) latex/report.bib
	cd latex ; pdflatex report ; pdflatex report ; bibtex report ; pdflatex report ; pdflatex report

latex/%.pdf: latex/%.tex latex/report.bib
	cd latex ; pdflatex $* ; pdflatex $* ; bibtex $* ; pdflatex $* ; pdflatex $*

pdf:
	okular latex/report.pdf&

